"""
Database Comparator for ICD-D06 Medicaid Provider File.

Queries actual state from all 4 pipeline stages and compares against
expected state generated by the ICD-D06 expected state generators.
"""
from typing import List, Dict, Any, Optional

from src.core.database import db, DatabaseManager
from src.core.config import settings
from src.core.models import MismatchRecord, ComparatorResult
from src.interfaces.base import BaseComparator


class IcdD06Comparator(BaseComparator):
    """
    Compares expected state against actual database state across all 4 stages
    for the ICD-D06 Medicaid Provider File.
    """

    def __init__(self, entity_id_prefix: str = None):
        self.entity_id_prefix = entity_id_prefix or settings.MCD_ID_PREFIX

    # =========================================================================
    # Stage 1: Compare against MedicaidProviderRaw
    # =========================================================================

    # Discriminator columns used to uniquely identify rows within the same
    # RecordType + MedicaidProviderNumber group.  Each record type that can
    # appear multiple times per provider needs a column (or columns) whose
    # value distinguishes one row from another.
    STAGE1_DISCRIMINATORS: Dict[str, List[str]] = {
        "02": ["Column3"],          # Address type code (S/M/P)
        "04": ["Column3"],          # Contract code (MEDSV/WVR/DENTL)
        "05": ["Column5"],          # Specialty code (100/110/200/300)
        "06": ["Column3"],          # NPI value
        "07": ["Column3"],          # Taxonomy code
        "10": ["Column3"],          # Waiver program code
        "11": ["Column3"],          # Waiver service code
        "12": ["Column3"],          # County/service area code
        "13": ["Column3"],          # License number
        "14": ["Column3"],          # Certification number
    }

    def compare_stage1(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """
        Compare expected raw rows against actual [CustomerInterfaceModule].[MedicaidProviderRaw].

        Uses key-based matching: for record types that can have multiple rows
        per provider, a discriminator column is used to pair the correct expected
        row with the correct actual row rather than relying on positional order.
        """
        result = ComparatorResult()

        actual_rows = db.execute_query(
            DatabaseManager.INTERFACE,
            """
            SELECT RecordType, MedicaidProviderNumber, 
                   Column3, Column4, Column5, Column6, Column7, Column8,
                   Column9, Column10, Column11, Column12, Column13, 
                   Column14, Column15, Column16, Column17
            FROM [CustomerInterfaceModule].[MedicaidProviderRaw]
            WHERE MedicaidProviderNumber LIKE ?
            ORDER BY MedicaidProviderNumber
            """,
            (f"{self.entity_id_prefix}%",),
        )

        # Build lookup: RecordType|MedicaidProviderNumber -> list of actual rows
        actual_by_key: Dict[str, List[Dict]] = {}
        for row in actual_rows:
            key = f"{row['RecordType']}|{row['MedicaidProviderNumber']}"
            actual_by_key.setdefault(key, []).append(row)

        for expected in expected_rows:
            line_num = expected["line_number"]
            rec_type = expected["RecordType"]
            mcd_id = expected["MedicaidProviderNumber"]

            if rec_type == "00":
                continue

            if not mcd_id.startswith(self.entity_id_prefix):
                continue

            key = f"{rec_type}|{mcd_id}"
            actual_matches = actual_by_key.get(key, [])

            if not actual_matches:
                result.add_mismatch(MismatchRecord(
                    source_line_number=line_num,
                    entity_id=mcd_id,
                    record_type=rec_type,
                    stage=1,
                    target_database=settings.INTERFACE_DB_NAME,
                    target_schema="CustomerInterfaceModule",
                    target_table="MedicaidProviderRaw",
                    target_column="(entire row)",
                    expected_value=f"RecordType={rec_type}",
                    actual_value=None,
                    status="MISSING",
                    error_category="MissingRow",
                    notes=f"Expected row for line {line_num} not found in MedicaidProviderRaw",
                ))
                continue

            # Key-based matching: find the actual row whose discriminator
            # column(s) match the expected values.
            actual = self._match_stage1_row(actual_matches, expected, rec_type)

            columns_to_check = ["RecordType", "MedicaidProviderNumber"] + [f"Column{i}" for i in range(3, 18)]

            for col in columns_to_check:
                exp_val = expected.get(col, "")
                act_val = str(actual.get(col, "")).strip() if actual.get(col) is not None else ""

                if exp_val == act_val:
                    result.add_pass()
                else:
                    result.add_mismatch(MismatchRecord(
                        source_line_number=line_num,
                        entity_id=mcd_id,
                        record_type=rec_type,
                        stage=1,
                        target_database=settings.INTERFACE_DB_NAME,
                        target_schema="CustomerInterfaceModule",
                        target_table="MedicaidProviderRaw",
                        target_column=col,
                        expected_value=exp_val,
                        actual_value=act_val,
                        status="FAIL",
                        error_category="FieldMismatch",
                    ))

        return result

    def _match_stage1_row(
        self, actual_rows: List[Dict], expected: Dict, rec_type: str
    ) -> Dict:
        """
        Find the actual row that matches the expected row using discriminator
        columns for the given record type.  Falls back to the first row when
        only one row exists or no discriminator is defined.
        """
        if len(actual_rows) == 1:
            return actual_rows[0]

        disc_cols = self.STAGE1_DISCRIMINATORS.get(rec_type)
        if not disc_cols:
            # No discriminator defined — single-row record type; take first.
            return actual_rows[0]

        for actual in actual_rows:
            match = True
            for col in disc_cols:
                exp_val = expected.get(col, "")
                act_val = str(actual.get(col, "")).strip() if actual.get(col) is not None else ""
                if exp_val != act_val:
                    match = False
                    break
            if match:
                return actual

        # Discriminator didn't match any row — return first as fallback so
        # comparison can still report field-level mismatches.
        return actual_rows[0]

    # =========================================================================
    # Stage 2: Compare against parsed record-type tables (Checksum-first)
    # =========================================================================

    def compare_stage2(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """
        Compare expected parsed fields against actual record-type tables.

        Uses checksum-first matching: groups expected columns by source line
        to form logical rows, finds an actual row where ALL columns match,
        then reports per-column differences only for unmatched rows.
        """
        result = ComparatorResult()

        # Group expectations by (entity_id, target_table, line_number) to form logical rows
        logical_rows: Dict[tuple, List[Dict]] = {}
        for exp in expected_rows:
            key = (exp["entity_id"], exp["target_table"], exp["line_number"])
            logical_rows.setdefault(key, []).append(exp)

        # Process by table to minimize DB queries
        tables_needed = set(exp["target_table"] for exp in expected_rows)
        actual_cache: Dict[str, List[Dict]] = {}
        for table_name in tables_needed:
            actual_cache[table_name] = self._query_stage2_table(table_name)

        for (mcd_id, table_name, line_num), columns in logical_rows.items():
            record_type = columns[0]["record_type"]

            # Build expected column→value map for this logical row
            expected_cols: Dict[str, str] = {}
            for exp in columns:
                expected_cols[exp["column_name"]] = exp["expected_value"] or ""

            # Get actual rows for this provider in this table
            all_actual = actual_cache.get(table_name, [])
            provider_rows = [
                r for r in all_actual
                if str(r.get("MedicaidProviderNumber", "")).strip() == mcd_id
            ]

            if not provider_rows:
                for col_name, exp_val in expected_cols.items():
                    result.add_mismatch(MismatchRecord(
                        source_line_number=line_num,
                        entity_id=mcd_id,
                        record_type=record_type,
                        stage=2,
                        target_database=settings.INTERFACE_DB_NAME,
                        target_schema="CustomerInterfaceModule",
                        target_table=table_name,
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=None,
                        status="MISSING",
                        error_category="MissingRow",
                    ))
                continue

            # Checksum-first: find an actual row where ALL expected columns match
            matched_row = self._find_full_match(provider_rows, expected_cols)

            if matched_row is not None:
                # Perfect row match — all columns pass
                result.pass_count += len(expected_cols)
            else:
                # No perfect match — find closest row and report per-column diffs
                best_row = self._find_closest_row(provider_rows, expected_cols)
                for col_name, exp_val in expected_cols.items():
                    act_val = str(best_row.get(col_name, "")).strip() if best_row.get(col_name) is not None else ""
                    if exp_val and "-" in exp_val and len(exp_val) == 10:
                        act_val = self._normalize_date(act_val)
                    if exp_val == act_val:
                        result.add_pass()
                    else:
                        result.add_mismatch(MismatchRecord(
                            source_line_number=line_num,
                            entity_id=mcd_id,
                            record_type=record_type,
                            stage=2,
                            target_database=settings.INTERFACE_DB_NAME,
                            target_schema="CustomerInterfaceModule",
                            target_table=table_name,
                            target_column=col_name,
                            expected_value=exp_val,
                            actual_value=act_val,
                            status="FAIL",
                            error_category="FieldMismatch",
                        ))

        return result

    # =========================================================================
    # Stage 3: Compare against Incoming tables (Checksum-first)
    # =========================================================================

    def compare_stage3(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """
        Compare expected transformed/mapped fields against actual Incoming tables.

        Uses checksum-first matching: groups expected columns by (entity_id,
        target_table, row_key) to form logical rows, finds an actual row where
        ALL columns match, then reports per-column differences only for
        unmatched rows.
        """
        result = ComparatorResult()

        # Group expectations by (entity_id, target_table, row_key) to form logical rows
        logical_rows: Dict[tuple, List[Dict]] = {}
        for row in expected_rows:
            key = (row["entity_id"], row["target_table"], row["row_key"])
            logical_rows.setdefault(key, []).append(row)

        # Process by table to minimize DB queries
        tables_needed = set(row["target_table"] for row in expected_rows)
        actual_cache: Dict[str, Dict[str, List[Dict]]] = {}
        for table_name in tables_needed:
            actual_rows = self._query_stage3_table(table_name)
            actual_cache[table_name] = self._group_incoming_by_provider(actual_rows)

        for (mcd_id, table_name, row_key), columns in logical_rows.items():
            record_type = columns[0].get("record_type", "")

            # Build expected column→value map for this logical row
            expected_cols: Dict[str, str] = {}
            metadata: Dict[str, Dict] = {}  # preserve business_rule/vocab per column
            for exp in columns:
                col_name = exp["target_column"]
                expected_cols[col_name] = exp["expected_value"] or ""
                metadata[col_name] = {
                    "business_rule": exp.get("business_rule"),
                    "vocab_used": exp.get("vocab_used"),
                }

            # Get actual rows for this provider
            provider_rows = actual_cache.get(table_name, {}).get(mcd_id, [])

            if not provider_rows:
                for col_name, exp_val in expected_cols.items():
                    meta = metadata.get(col_name, {})
                    result.add_mismatch(MismatchRecord(
                        source_line_number=0,
                        entity_id=mcd_id,
                        record_type=record_type,
                        stage=3,
                        target_database=settings.INTERFACE_DB_NAME,
                        target_schema="InterfaceModule",
                        target_table=table_name,
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=None,
                        status="MISSING",
                        error_category="MissingRow",
                        business_rule=meta.get("business_rule"),
                        vocab_used=meta.get("vocab_used"),
                        notes=f"RowKey: {row_key}",
                    ))
                continue

            # Checksum-first: find an actual row where ALL expected columns match
            matched_row = self._find_full_match(provider_rows, expected_cols)

            if matched_row is not None:
                # Perfect row match — all columns pass
                result.pass_count += len(expected_cols)
            else:
                # No perfect match — find closest row and report per-column diffs
                best_row = self._find_closest_row(provider_rows, expected_cols)
                for col_name, exp_val in expected_cols.items():
                    meta = metadata.get(col_name, {})
                    act_val = str(best_row.get(col_name, "")).strip() if best_row.get(col_name) is not None else ""
                    if exp_val == act_val:
                        result.add_pass()
                    else:
                        result.add_mismatch(MismatchRecord(
                            source_line_number=0,
                            entity_id=mcd_id,
                            record_type=record_type,
                            stage=3,
                            target_database=settings.INTERFACE_DB_NAME,
                            target_schema="InterfaceModule",
                            target_table=table_name,
                            target_column=col_name,
                            expected_value=exp_val,
                            actual_value=act_val,
                            status="FAIL",
                            error_category="FieldMismatch" if not meta.get("vocab_used") else "Lookup",
                            business_rule=meta.get("business_rule"),
                            vocab_used=meta.get("vocab_used"),
                            notes=f"RowKey: {row_key}",
                        ))

        return result

    # =========================================================================
    # Checksum-first matching helpers
    # =========================================================================

    def _find_full_match(self, actual_rows: List[Dict], expected_cols: Dict[str, str]) -> Optional[Dict]:
        """
        Find an actual row where ALL expected columns match exactly.
        Returns the matched row, or None if no perfect match exists.
        """
        for actual_row in actual_rows:
            all_match = True
            for col_name, exp_val in expected_cols.items():
                act_val = str(actual_row.get(col_name, "")).strip() if actual_row.get(col_name) is not None else ""
                # Normalize dates for comparison
                if exp_val and "-" in exp_val and len(exp_val) == 10:
                    act_val = self._normalize_date(act_val)
                if exp_val != act_val:
                    all_match = False
                    break
            if all_match:
                return actual_row
        return None

    def _find_closest_row(self, actual_rows: List[Dict], expected_cols: Dict[str, str]) -> Dict:
        """
        Find the actual row with the fewest column differences from expected.
        Used when no perfect match exists to provide the best diagnostic output.
        """
        if not actual_rows:
            return {}
        if len(actual_rows) == 1:
            return actual_rows[0]

        best_row = actual_rows[0]
        best_score = -1

        for actual_row in actual_rows:
            score = 0
            for col_name, exp_val in expected_cols.items():
                act_val = str(actual_row.get(col_name, "")).strip() if actual_row.get(col_name) is not None else ""
                if exp_val and "-" in exp_val and len(exp_val) == 10:
                    act_val = self._normalize_date(act_val)
                if exp_val == act_val:
                    score += 1
            if score > best_score:
                best_score = score
                best_row = actual_row

        return best_row

    # =========================================================================
    # Stage 4: Compare against final Carity tables
    # =========================================================================

    def compare_stage4(self, stage3_expected: List[Dict[str, Any]]) -> ComparatorResult:
        """
        Compare Stage 3 expected values against the final Carity DB tables.
        Since Stage 3→4 is a straight copy, expected values are the same.
        Column names are mapped from IncomingModule format to Carity format where they differ.
        """
        result = ComparatorResult()

        table_map = {
            "IncomingOrganization": ("OrganizationModule", "Organization"),
            "IncomingLocation": ("OrganizationModule", "Location"),
            "IncomingOrganizationAddresses": ("OrganizationModule", "OrganizationAddresses"),
            "IncomingLocationAddresses": ("OrganizationModule", "LocationAddresses"),
            "IncomingOrganizationEmailAddresses": ("OrganizationModule", "OrganizationEmailAddresses"),
            "IncomingLocationEmailAddresses": ("OrganizationModule", "LocationEmailAddresses"),
            "IncomingOrganizationIdentifiers": ("OrganizationModule", "OrganizationIdentifiers"),
            "IncomingLocationIdentifiers": ("OrganizationModule", "LocationIdentifiers"),
            "IncomingOrganizationPhones": ("OrganizationModule", "OrganizationPhones"),
            "IncomingLocationPhones": ("OrganizationModule", "LocationPhones"),
            "IncomingLocationType": ("OrganizationModule", "LocationType"),
            "IncomingLocationTypeSubtypes": ("OrganizationModule", "LocationTypeSubtypes"),
            "IncomingOrganizationCredentials": ("OrganizationModule", "OrganizationCredentials"),
            "IncomingLocationCredentials": ("OrganizationModule", "LocationCredentials"),
            "IncomingOrganizationBusinessTypes": ("OrganizationModule", "OrganizationBusinessTypes"),
            "IncomingOrganizationOrganizationTypes": ("OrganizationModule", "OrganizationOrganizationTypes"),
            "IncomingLocationSpecialty": ("OrganizationModule", "LocationSpecialty"),
            "IncomingLocationTaxonomies": ("OrganizationModule", "LocationTaxonomies"),
            "IncomingOrganizationSupportedPrograms": ("OrganizationModule", "OrganizationSupportedPrograms"),
            "IncomingLocationSupportedPrograms": ("OrganizationModule", "LocationSupportedPrograms"),
            "IncomingOrganizationPointOfContact": ("OrganizationModule", "OrganizationPointOfContact"),
            "IncomingLocationPointOfContact": ("OrganizationModule", "LocationPointOfContact"),
            "IncomingOrganizationPointOfContactAssociatedPrograms": ("OrganizationModule", "OrganizationPointOfContactAssociatedPrograms"),
            "IncomingLocationPointOfContactAssociatedPrograms": ("OrganizationModule", "LocationPointOfContactAssociatedPrograms"),
            "IncomingPaymentSuspension": ("OrganizationModule", "PaymentSuspension"),
            "IncomingLocationExtensionWaiverServices": ("CustomerOrganizationModule", "LocationExtensionWaiverService"),
        }

        # Column name mappings: Incoming table columns → Carity table columns
        # Only needed where column names differ between IncomingModule and OrganizationModule
        # Note: OrganizationAddresses keeps "OrganizationPhysicalAddressTypeDisplayName" as-is
        # LocationAddresses uses "PhysicalAddressTypeDisplayName" (same as IncomingLocationAddresses)
        # No mapping needed — both already match their respective Carity tables

        by_table: Dict[str, List[Dict]] = {}
        for row in stage3_expected:
            by_table.setdefault(row["target_table"], []).append(row)

        for incoming_table, expectations in by_table.items():
            mapping = table_map.get(incoming_table)
            if not mapping:
                continue

            final_schema, final_table = mapping
            actual_rows = self._query_stage4_table(final_schema, final_table)
            actual_by_provider = self._group_carity_by_provider(actual_rows)

            for exp in expectations:
                mcd_id = exp["entity_id"]
                # Column names match directly between Incoming and Carity tables
                col_name = exp["target_column"]
                exp_val = exp["expected_value"] or ""

                provider_rows = actual_by_provider.get(mcd_id, [])
                if not provider_rows:
                    result.add_mismatch(MismatchRecord(
                        source_line_number=0,
                        entity_id=mcd_id,
                        record_type=exp.get("record_type", ""),
                        stage=4,
                        target_database=settings.CARITY_DB_NAME,
                        target_schema=final_schema,
                        target_table=final_table,
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=None,
                        status="MISSING",
                        error_category="MissingRow",
                    ))
                    continue

                found_match = False
                for actual_row in provider_rows:
                    act_val = str(actual_row.get(col_name, "")).strip() if actual_row.get(col_name) is not None else ""
                    if exp_val == act_val:
                        found_match = True
                        break

                if found_match:
                    result.add_pass()
                else:
                    act_val = str(provider_rows[0].get(col_name, "")).strip() if provider_rows[0].get(col_name) is not None else ""
                    result.add_mismatch(MismatchRecord(
                        source_line_number=0,
                        entity_id=mcd_id,
                        record_type=exp.get("record_type", ""),
                        stage=4,
                        target_database=settings.CARITY_DB_NAME,
                        target_schema=final_schema,
                        target_table=final_table,
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=act_val,
                        status="FAIL",
                        error_category="FieldMismatch",
                    ))

        return result

    # =========================================================================
    # Query helpers
    # =========================================================================

    def _query_stage2_table(self, table_name: str) -> List[Dict]:
        """Query a Stage 2 parsed table filtered by our entity ID prefix."""
        try:
            return db.execute_query(
                DatabaseManager.INTERFACE,
                f"SELECT * FROM [CustomerInterfaceModule].[{table_name}] WHERE MedicaidProviderNumber LIKE ?",
                (f"{self.entity_id_prefix}%",),
            )
        except Exception:
            return []

    def _query_stage3_table(self, table_name: str) -> List[Dict]:
        """Query a Stage 3 Incoming table."""
        # CustomerInterfaceModule tables
        customer_tables = ["IncomingLocationExtensionWaiverServices", "IncomingLocationExtension"]
        schema = "CustomerInterfaceModule" if table_name in customer_tables else "InterfaceModule"

        try:
            return db.execute_query(
                DatabaseManager.INTERFACE,
                f"SELECT * FROM [{schema}].[{table_name}] WHERE CustomerProviderIdentifier LIKE ?",
                (f"{self.entity_id_prefix}%",),
            )
        except Exception:
            try:
                return db.execute_query(
                    DatabaseManager.INTERFACE,
                    f"SELECT TOP 1000 * FROM [{schema}].[{table_name}]",
                )
            except Exception:
                return []

    def _query_stage4_table(self, schema: str, table_name: str) -> List[Dict]:
        """
        Query a Stage 4 final Carity table, enriching rows with the
        provider identifier for grouping (as _ProviderNumber).
        """
        try:
            if table_name == "Organization":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT o.*, oi.Value AS _ProviderNumber
                        FROM [{schema}].[Organization] o
                        INNER JOIN [{schema}].[OrganizationIdentifiers] oi
                            ON o.OrganizationKey = oi.OrganizationKey
                        WHERE oi.TypeIdentifier = 1000003 AND oi.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name == "Location":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT l.*, li.Value AS _ProviderNumber
                        FROM [{schema}].[Location] l
                        INNER JOIN [{schema}].[LocationIdentifiers] li
                            ON l.LocationKey = li.LocationKey
                        WHERE li.TypeIdentifier = 1000003 AND li.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name == "OrganizationIdentifiers":
                # Don't self-join — just filter directly
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT oi.*, oi2.Value AS _ProviderNumber
                        FROM [{schema}].[OrganizationIdentifiers] oi
                        INNER JOIN [{schema}].[OrganizationIdentifiers] oi2
                            ON oi.OrganizationKey = oi2.OrganizationKey AND oi2.TypeIdentifier = 1000003
                        WHERE oi2.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name == "LocationIdentifiers":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT li.*, li2.Value AS _ProviderNumber
                        FROM [{schema}].[LocationIdentifiers] li
                        INNER JOIN [{schema}].[LocationIdentifiers] li2
                            ON li.LocationKey = li2.LocationKey AND li2.TypeIdentifier = 1000003
                        WHERE li2.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name in ("OrganizationAddresses", "OrganizationCredentials",
                                "OrganizationBusinessTypes", "OrganizationEmailAddresses",
                                "OrganizationPhones", "OrganizationOrganizationTypes",
                                "OrganizationSupportedPrograms", "OrganizationPointOfContact"):
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT t.*, id.Value AS _ProviderNumber
                        FROM [{schema}].[{table_name}] t
                        INNER JOIN [{schema}].[OrganizationIdentifiers] id
                            ON t.OrganizationKey = id.OrganizationKey AND id.TypeIdentifier = 1000003
                        WHERE id.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name == "OrganizationPointOfContactAssociatedPrograms":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT ap.*, id.Value AS _ProviderNumber
                        FROM [{schema}].[OrganizationPointOfContactAssociatedPrograms] ap
                        INNER JOIN [{schema}].[OrganizationPointOfContact] poc
                            ON poc.OrganizationPointOfContactKey = ap.OrganizationPointOfContactKey
                        INNER JOIN [{schema}].[OrganizationIdentifiers] id
                            ON poc.OrganizationKey = id.OrganizationKey AND id.TypeIdentifier = 1000003
                        WHERE id.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name in ("LocationAddresses", "LocationCredentials", "LocationSpecialty",
                                "LocationEmailAddresses", "LocationPhones", "LocationType",
                                "LocationTypeSubtypes", "LocationTaxonomies",
                                "LocationSupportedPrograms", "LocationPointOfContact",
                                "PaymentSuspension"):
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT t.*, id.Value AS _ProviderNumber
                        FROM [{schema}].[{table_name}] t
                        INNER JOIN [{schema}].[LocationIdentifiers] id
                            ON t.LocationKey = id.LocationKey AND id.TypeIdentifier = 1000003
                        WHERE id.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name == "LocationPointOfContactAssociatedPrograms":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT ap.*, id.Value AS _ProviderNumber
                        FROM [{schema}].[LocationPointOfContactAssociatedPrograms] ap
                        INNER JOIN [{schema}].[LocationPointOfContact] poc
                            ON poc.LocationPointOfContactKey = ap.LocationPointOfContactKey
                        INNER JOIN [{schema}].[Location] loc
                            ON loc.LocationKey = poc.LocationKey
                        INNER JOIN [{schema}].[LocationIdentifiers] id
                            ON loc.LocationKey = id.LocationKey AND id.TypeIdentifier = 1000003
                        WHERE id.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            elif table_name == "LocationExtensionWaiverService":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT t.*, id.Value AS _ProviderNumber
                        FROM [{schema}].[{table_name}] t
                        INNER JOIN [OrganizationModule].[LocationIdentifiers] id
                            ON t.LocationKey = id.LocationKey AND id.TypeIdentifier = 1000003
                        WHERE id.Value LIKE ?""",
                    (f"{self.entity_id_prefix}%",),
                )
            else:
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"SELECT TOP 1000 * FROM [{schema}].[{table_name}]",
                )
        except Exception:
            return []

    def _group_incoming_by_provider(self, rows: List[Dict]) -> Dict[str, List[Dict]]:
        """Group Incoming table rows by provider MCD ID."""
        grouped: Dict[str, List[Dict]] = {}
        for row in rows:
            pid = str(row.get("CustomerProviderIdentifier", "")).strip()
            if pid:
                grouped.setdefault(pid, []).append(row)
        return grouped

    def _group_carity_by_provider(self, rows: List[Dict]) -> Dict[str, List[Dict]]:
        """Group final Carity table rows by provider using the _ProviderNumber alias."""
        grouped: Dict[str, List[Dict]] = {}
        for row in rows:
            # _ProviderNumber is the aliased Medicaid Provider ID from the JOIN
            pid = None
            if "_ProviderNumber" in row and row["_ProviderNumber"]:
                pid = str(row["_ProviderNumber"]).strip()
            else:
                # Fallback for tables not enriched
                for col in ["Value", "BusinessProfileFullName", "BusinessProfileShortName"]:
                    if col in row and row[col]:
                        pid = str(row[col]).strip()
                        break
            if pid:
                grouped.setdefault(pid, []).append(row)
        return grouped

    @staticmethod
    def _normalize_date(value: str) -> str:
        """Normalize date values for comparison."""
        if not value:
            return ""
        if " " in value:
            value = value.split(" ")[0]
        if "T" in value:
            value = value.split("T")[0]
        return value.strip()
