"""
CLI Interface for the Test Data Generator tool.

Simplified tool: takes a YAML/JSON spec as input, generates test data files and SQL scripts.

Commands:
  generate       — Generate test data files from a spec
  generate-sql   — Generate SQL insert/cleanup scripts from a spec
  list-scenarios — List all available test scenario types

Usage:
  python -m tools.src.cli generate --spec tools/specs/icd_d12.yaml --output data/icd_d12/
  python -m tools.src.cli generate-sql --spec tools/specs/icd_d12.yaml --output data/icd_d12/
  python -m tools.src.cli list-scenarios
"""
import os
import sys
import argparse
import json

# Ensure the project root is on the path
_PL_TEST_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PL_TEST_ROOT not in sys.path:
    sys.path.insert(0, _PL_TEST_ROOT)

from tools.src.models import (
    InterfaceSpec, ScenarioType,
    STANDARD_SCENARIOS, EXTENDED_SCENARIOS, ALL_SCENARIOS,
)


def _load_spec(spec_path: str) -> InterfaceSpec:
    """Load an InterfaceSpec from a YAML or JSON file."""
    if not os.path.exists(spec_path):
        print(f"ERROR: Spec file not found: {spec_path}")
        sys.exit(1)

    with open(spec_path, "r", encoding="utf-8") as f:
        if spec_path.endswith(".json"):
            data = json.load(f)
        else:
            import yaml
            data = yaml.safe_load(f)

    return InterfaceSpec(**data)


def cmd_generate(spec_path: str, output_dir: str, scenarios: str = "standard", volume_size: int = 50):
    """Generate test data files from a YAML/JSON spec."""
    spec = _load_spec(spec_path)
    spec.test_scenarios.volume_size = volume_size

    # Parse scenario list
    if scenarios == "all":
        selected = ALL_SCENARIOS
    elif scenarios == "standard":
        selected = STANDARD_SCENARIOS
    else:
        selected = [ScenarioType(s.strip()) for s in scenarios.split(",")]

    from tools.src.generators.file_generator import FileGenerator
    from tools.src.generators.readme_generator import ReadmeGenerator

    gen = FileGenerator(spec)
    generated_files = gen.generate_all(output_dir, selected)

    readme_gen = ReadmeGenerator(spec)
    readme_path = readme_gen.generate(output_dir, generated_files)

    print(f"Generated {len(generated_files)} test files in: {output_dir}")
    for f in generated_files:
        print(f"  {os.path.basename(f)}")
    print(f"  {os.path.basename(readme_path)}")


def cmd_generate_sql(spec_path: str, output_dir: str):
    """Generate SQL insert/cleanup scripts from a YAML/JSON spec."""
    spec = _load_spec(spec_path)

    from tools.src.generators.sql_generator import SqlGenerator

    gen = SqlGenerator(spec)
    generated = gen.generate_all(output_dir)

    print(f"Generated {len(generated)} SQL scripts in: {output_dir}")
    for f in generated:
        print(f"  {os.path.basename(f)}")


def cmd_list_scenarios():
    """List all available test scenario types."""
    print("Standard Scenarios (always generated by default):")
    print("-" * 55)
    for s in STANDARD_SCENARIOS:
        print(f"  {s.value:<20} - {_scenario_description(s)}")

    print("\nExtended Scenarios (opt-in via --scenarios flag):")
    print("-" * 55)
    for s in EXTENDED_SCENARIOS:
        print(f"  {s.value:<20} - {_scenario_description(s)}")

    print("\nUsage:")
    print("  --scenarios standard          (default: all 8 standard)")
    print("  --scenarios all               (standard + extended = 16)")
    print("  --scenarios baseline,all_codes,large_volume  (specific list)")


def _scenario_description(s: ScenarioType) -> str:
    descs = {
        ScenarioType.BASELINE: "Happy-path, 3 entities, all fields populated",
        ScenarioType.MAX_LENGTHS: "All fields at maximum documented length",
        ScenarioType.MIN_EMPTY: "Only required fields; optional fields blank",
        ScenarioType.BOUNDARY_DATES: "Edge dates: Jan 1, Dec 31, leap day, 99991231",
        ScenarioType.ALL_CODES: "Every valid code value from code tables exercised",
        ScenarioType.SPECIAL_CHARS: "Apostrophes, hyphens, ampersands in text fields",
        ScenarioType.LARGE_VOLUME: "N entities for performance testing (default 50)",
        ScenarioType.COMPOSITE_RULES: "Business rule boundary conditions",
        ScenarioType.CROSS_FIELD: "Fields that affect each other's validity",
        ScenarioType.DUPLICATES: "Same entity appearing twice in one file",
        ScenarioType.ORDERING: "Records in unexpected order within file",
        ScenarioType.ENCODING: "UTF-8 BOM, extended ASCII, multi-byte characters",
        ScenarioType.TRUNCATION: "Data slightly over max length (system should handle)",
        ScenarioType.REFERENTIAL: "Child without parent, parent without children",
        ScenarioType.HISTORICAL: "Multi-day feed simulation (day 0, day 1, day 2)",
        ScenarioType.CODE_COVERAGE: "Every code value exercised per entity",
    }
    return descs.get(s, "")


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="tools.cli",
        description="Test Data Generator - Generate test files and SQL from a YAML/JSON spec",
    )
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # generate
    p = subparsers.add_parser("generate", help="Generate test data files")
    p.add_argument("--spec", "-s", required=True, help="Path to spec YAML/JSON file")
    p.add_argument("--output", "-o", required=True, help="Output directory for test files")
    p.add_argument("--scenarios", default="standard", help="standard | all | comma-separated list")
    p.add_argument("--volume-size", type=int, default=50, help="Entity count for large_volume scenario")

    # generate-sql
    p = subparsers.add_parser("generate-sql", help="Generate SQL insert/cleanup scripts")
    p.add_argument("--spec", "-s", required=True, help="Path to spec YAML/JSON file")
    p.add_argument("--output", "-o", required=True, help="Output directory for SQL scripts")

    # list-scenarios
    subparsers.add_parser("list-scenarios", help="List available test scenario types")

    args = parser.parse_args()

    if args.command == "generate":
        cmd_generate(args.spec, args.output, args.scenarios, args.volume_size)
    elif args.command == "generate-sql":
        cmd_generate_sql(args.spec, args.output)
    elif args.command == "list-scenarios":
        cmd_list_scenarios()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
