"""
Scaffold Generator — produces Python plugin skeleton for a new interface.

Generates models.py, parser.py, expected_state.py, comparator.py, plugin.py,
vocab_config.py, __init__.py, and test_parser.py with TODO markers.
"""
import os
from typing import List

from tools.src.models import InterfaceSpec, FieldDefinition, FormatType


class ScaffoldGenerator:
    """Generates a complete Python interface plugin scaffold."""

    def __init__(self, spec: InterfaceSpec):
        self.spec = spec

    def generate(self, output_dir: str, register: bool = False) -> List[str]:
        """
        Generate the plugin scaffold.
        
        Args:
            output_dir: Where to create the plugin directory
            register: Whether to add import to interfaces/__init__.py
            
        Returns:
            List of generated file paths.
        """
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, "tests"), exist_ok=True)
        generated: List[str] = []

        generated.append(self._write(output_dir, "__init__.py", self._gen_init()))
        generated.append(self._write(output_dir, "models.py", self._gen_models()))
        generated.append(self._write(output_dir, "parser.py", self._gen_parser()))
        generated.append(self._write(output_dir, "expected_state.py", self._gen_expected_state()))
        generated.append(self._write(output_dir, "comparator.py", self._gen_comparator()))
        generated.append(self._write(output_dir, "plugin.py", self._gen_plugin()))
        generated.append(self._write(output_dir, "vocab_config.py", self._gen_vocab_config()))
        generated.append(self._write(os.path.join(output_dir, "tests"), "__init__.py", ""))
        generated.append(self._write(os.path.join(output_dir, "tests"), "test_parser.py", self._gen_test()))

        return generated

    def _write(self, directory: str, filename: str, content: str) -> str:
        """Write content to a file."""
        filepath = os.path.join(directory, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return filepath

    # =========================================================================
    # Code Generation
    # =========================================================================

    def _gen_init(self) -> str:
        s = self.spec
        itype = s.meta.interface_type
        class_prefix = self._class_prefix()
        return f'''"""
{s.meta.display_name} interface plugin.

This module registers the {itype} plugin with the interface registry on import.
"""
from src.interfaces.{itype}.plugin import {class_prefix}Plugin
from src.interfaces import register

# Register this plugin with the framework
register({class_prefix}Plugin())
'''

    def _gen_models(self) -> str:
        s = self.spec
        class_prefix = self._class_prefix()
        fields_code = self._gen_dataclass_fields()
        return f'''"""
Data models for the {s.meta.display_name}.

Auto-generated by Test Data Generator tool.
TODO: Review and adjust field types/lengths as needed.
"""
from dataclasses import dataclass, field
from typing import Optional, List

from src.interfaces.base import BaseParsedFile


@dataclass
class SourceLine:
    """Represents a single line from the source file."""
    line_number: int
    raw_text: str
    record_type: str


@dataclass
class DetailRecord:
    """Detail record — one per entity."""
    line_number: int
    record_type: str
{fields_code}


@dataclass
class ParsedFile(BaseParsedFile):
    """Complete parsed representation of the file."""
    members: dict = field(default_factory=dict)  # entity_id → DetailRecord

    @property
    def record_count(self) -> int:
        return len(self.members)

    @property
    def entity_count(self) -> int:
        return len(self.members)

    @property
    def entity_ids(self) -> List[str]:
        return list(self.members.keys())
'''

    def _gen_parser(self) -> str:
        s = self.spec
        class_prefix = self._class_prefix()
        itype = s.meta.interface_type
        fmt = s.format.type.value
        return f'''"""
Parser for the {s.meta.display_name}.
Format: {fmt}

Auto-generated by Test Data Generator tool.
TODO: Implement parse logic for your specific file format.
"""
from typing import List, Tuple

from src.interfaces.base import BaseParser
from src.interfaces.{itype}.models import SourceLine, DetailRecord, ParsedFile


class {class_prefix}Parser(BaseParser):
    """Parses {s.meta.display_name} files."""

    def parse_file(self, filepath: str) -> ParsedFile:
        """Parse from local filesystem."""
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        return self.parse_content(content, filename=filepath)

    def parse_content(self, content: str, filename: str = "unknown") -> ParsedFile:
        """Parse file content from a string."""
        parsed = ParsedFile(filename=filename)
        lines = content.splitlines()

        for line_number, raw_text in enumerate(lines, start=1):
            if not raw_text.strip():
                continue

            # TODO: Implement record type detection logic
            record_type = "DTL"  # Default — adjust based on format

            source_line = SourceLine(
                line_number=line_number,
                raw_text=raw_text,
                record_type=record_type,
            )
            parsed.source_lines.append(source_line)

            if record_type == "DTL":
                detail = self._parse_detail(line_number, raw_text)
                parsed.members[detail.{s.entity.id_field}] = detail

        return parsed

    def _parse_detail(self, line_number: int, raw_text: str) -> DetailRecord:
        """Parse a detail record.
        
        TODO: Implement field extraction for {fmt} format.
        """
        # TODO: Extract fields from raw_text based on format type
        raise NotImplementedError("Implement detail record parsing")
'''

    def _gen_expected_state(self) -> str:
        s = self.spec
        class_prefix = self._class_prefix()
        itype = s.meta.interface_type
        return f'''"""
Expected State Generator for {s.meta.display_name}.

Auto-generated by Test Data Generator tool.
TODO: Implement business rule logic for Stage 3.
"""
from typing import List, Dict, Any, Optional

from src.interfaces.base import BaseExpectedStateGenerator, BaseParsedFile
from src.interfaces.{itype}.models import ParsedFile, DetailRecord


class {class_prefix}ExpectedStateGenerator(BaseExpectedStateGenerator):
    """Generates expected state for all 4 stages."""

    def __init__(self, parsed_file: BaseParsedFile, vocab_client=None):
        if not isinstance(parsed_file, ParsedFile):
            raise TypeError("{class_prefix}ExpectedStateGenerator requires a {itype} ParsedFile")
        self.parsed_file: ParsedFile = parsed_file
        self.vocab_client = vocab_client

    def generate_stage1(self) -> List[Dict[str, Any]]:
        """Stage 1: One raw row per source line."""
        return [
            {{"line_number": sl.line_number, "RecordType": sl.record_type, "RawText": sl.raw_text}}
            for sl in self.parsed_file.source_lines
        ]

    def generate_stage2(self) -> List[Dict[str, Any]]:
        """Stage 2: Parsed fields (EAV format).
        
        TODO: Implement field-level expected state.
        """
        raise NotImplementedError("Implement Stage 2 expected state")

    def generate_stage3(self) -> List[Dict[str, Any]]:
        """Stage 3: Transformed/Incoming.
        
        TODO: Implement business rule transformations.
        """
        raise NotImplementedError("Implement Stage 3 expected state")

    def generate_stage4(self) -> List[Dict[str, Any]]:
        """Stage 4: Final (straight copy from Stage 3)."""
        return self.generate_stage3()
'''

    def _gen_comparator(self) -> str:
        s = self.spec
        class_prefix = self._class_prefix()
        itype = s.meta.interface_type
        return f'''"""
Database Comparator for {s.meta.display_name}.

Auto-generated by Test Data Generator tool.
TODO: Implement stage queries and comparison logic.
"""
from typing import List, Dict, Any

from src.core.database import db, DatabaseManager
from src.core.config import settings
from src.core.models import MismatchRecord, ComparatorResult
from src.interfaces.base import BaseComparator


class {class_prefix}Comparator(BaseComparator):
    """Compares expected vs actual for {s.meta.display_name}."""

    def __init__(self, entity_id_prefix: str = None):
        self.entity_id_prefix = entity_id_prefix or "{s.entity.test_prefix}"

    def compare_stage1(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """Compare Stage 1 (Raw).
        
        TODO: Implement raw row comparison.
        """
        return ComparatorResult()

    def compare_stage2(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """Compare Stage 2 (Parsed).
        
        TODO: Implement parsed field comparison.
        """
        return ComparatorResult()

    def compare_stage3(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """Compare Stage 3 (Incoming/Transformed).
        
        TODO: Implement transformed state comparison.
        """
        return ComparatorResult()

    def compare_stage4(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """Compare Stage 4 (Final).
        
        TODO: Implement final state comparison.
        """
        return ComparatorResult()
'''

    def _gen_plugin(self) -> str:
        s = self.spec
        class_prefix = self._class_prefix()
        itype = s.meta.interface_type
        return f'''"""
{s.meta.display_name} Plugin.

Auto-generated by Test Data Generator tool.
"""
from typing import List, Dict, Optional, Any

from src.interfaces.base import (
    InterfacePlugin, BaseParser, BaseExpectedStateGenerator,
    BaseComparator, BaseParsedFile,
)
from src.interfaces.{itype}.vocab_config import VOCAB_LOOKUP_KEYS


class {class_prefix}Plugin(InterfacePlugin):
    """{s.meta.display_name} interface plugin."""

    @property
    def interface_type(self) -> str:
        return "{itype}"

    @property
    def display_name(self) -> str:
        return "{s.meta.display_name}"

    @property
    def file_extensions(self) -> List[str]:
        return ["{s.meta.file_extension}"]

    @property
    def entity_id_field_name(self) -> str:
        return "{s.entity.id_field.replace("_", " ").title().replace(" ", "")}"

    @property
    def description(self) -> str:
        return "{s.meta.description}"

    @property
    def vocab_lookup_keys(self) -> Dict[str, str]:
        return VOCAB_LOOKUP_KEYS

    def create_parser(self) -> BaseParser:
        from src.interfaces.{itype}.parser import {class_prefix}Parser
        return {class_prefix}Parser()

    def create_expected_state_generator(
        self, parsed_file: BaseParsedFile, vocab_client: Optional[Any] = None
    ) -> BaseExpectedStateGenerator:
        from src.interfaces.{itype}.expected_state import {class_prefix}ExpectedStateGenerator
        return {class_prefix}ExpectedStateGenerator(parsed_file, vocab_client)

    def create_comparator(self, entity_id_prefix: str) -> BaseComparator:
        from src.interfaces.{itype}.comparator import {class_prefix}Comparator
        return {class_prefix}Comparator(entity_id_prefix)

    @property
    def pipeline_cleanup_config(self):
        """Stages 1-3 cleanup targets.
        
        TODO: Define cleanup targets for this interface.
        """
        return []

    @property
    def carity_cleanup_config(self):
        """Stage 4 cleanup targets.
        
        TODO: Define Stage 4 cleanup targets.
        """
        return []
'''

    def _gen_vocab_config(self) -> str:
        s = self.spec
        itype = s.meta.interface_type
        return f'''"""
{s.meta.display_name} Vocabulary Lookup Key mappings.

Auto-generated by Test Data Generator tool.
TODO: Map source code fields to VocabularyLookup definitions.
"""

VOCAB_LOOKUP_KEYS = {{
    # TODO: Add vocabulary mappings for code fields
    # "field_name": "CustomerSystemName.CustomerTableName.CustomerColumnName",
}}
'''

    def _gen_test(self) -> str:
        s = self.spec
        class_prefix = self._class_prefix()
        itype = s.meta.interface_type
        return f'''"""
Unit tests for {s.meta.display_name} parser.

Auto-generated by Test Data Generator tool.
"""
import os
import sys
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))))

from src.interfaces.{itype}.parser import {class_prefix}Parser
from src.interfaces.{itype}.models import ParsedFile


_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))))
DATA_DIR = os.path.join(_PROJECT_ROOT, "data", "{itype}")


@pytest.fixture
def parser():
    return {class_prefix}Parser()


class TestPluginRegistry:
    """Tests for plugin registration."""

    def test_{itype}_registered(self):
        from src.interfaces import list_interface_types
        assert "{itype}" in list_interface_types()

    def test_get_plugin(self):
        from src.interfaces import get_interface
        plugin = get_interface("{itype}")
        assert plugin.interface_type == "{itype}"
        assert "{s.meta.file_extension}" in plugin.file_extensions


# TODO: Add parser tests once implementation is complete
'''

    # =========================================================================
    # Helpers
    # =========================================================================

    def _class_prefix(self) -> str:
        """Generate PascalCase class prefix from interface_type."""
        parts = self.spec.meta.interface_type.split("_")
        return "".join(p.capitalize() for p in parts)

    def _gen_dataclass_fields(self) -> str:
        """Generate dataclass field declarations for DetailRecord."""
        lines = []
        for field in self.spec.detail_fields:
            comment = f"  # {field.description}" if field.description else ""
            lines.append(f"    {field.name}: str{comment}")
        return "\n".join(lines) if lines else "    pass  # TODO: Add fields"
