"""
Database Comparator for ICD-D12 FSIA File.

Queries actual state from pipeline stages and compares against
expected state generated by the ICD-D12 expected state generator.

Stage 1: [CustomerInterfaceModule].[LongTermCareFunctionalScreenFormRaw] — raw lines
Stage 2: [CustomerInterfaceModule].[LongTermCareFunctionalScreenForm] — parsed fields
Stage 3: SKIPPED — no intermediate transformation in Interface DB
Stage 4: [CustomFormModule] tables in Carity DB — form instances & field answers
         (CustomFormDefinitionKey: 964B0DFB-ED99-4F5A-8449-B43C013B9062, Version 55)
"""
from typing import List, Dict, Any, Optional

from src.core.database import db, DatabaseManager
from src.core.config import settings
from src.core.models import MismatchRecord, ComparatorResult
from src.interfaces.base import BaseComparator


class IcdD12Comparator(BaseComparator):
    """
    Compares expected state against actual database state across all 4 stages
    for the ICD-D12 FSIA File.
    """

    def __init__(self, entity_id_prefix: str = None):
        self.entity_id_prefix = entity_id_prefix or "9999999"

    # =========================================================================
    # Stage 1: Compare against FsiaRaw (raw lines)
    # =========================================================================

    def compare_stage1(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """Compare expected raw rows against actual LongTermCareFunctionalScreenFormRaw table.

        This table only has two columns: InterfaceBatchKey and RawText.
        We filter by searching RawText for lines starting with the entity_id_prefix.
        """
        result = ComparatorResult()

        try:
            actual_rows = db.execute_query(
                DatabaseManager.INTERFACE,
                """
                SELECT RawText
                FROM [CustomerInterfaceModule].[LongTermCareFunctionalScreenFormRaw]
                WHERE RawText LIKE ?
                ORDER BY RawText
                """,
                (f"{self.entity_id_prefix}%",),
            )
        except Exception:
            actual_rows = []

        # Build a set of actual raw texts (trimmed) for matching
        actual_texts = [r["RawText"].rstrip() for r in actual_rows if r.get("RawText")]

        for expected in expected_rows:
            line_num = expected["line_number"]
            rec_type = expected["RecordType"]

            # Skip HDR — only compare DTL records
            if rec_type == "HDR":
                continue

            exp_text = expected.get("RawText", "").rstrip()
            entity_id = exp_text[:10].strip() if exp_text else ""

            # Find matching raw text in actuals
            matched = False
            for act_text in actual_texts:
                if act_text.rstrip() == exp_text:
                    matched = True
                    break

            if matched:
                result.add_pass(MismatchRecord(
                    source_line_number=line_num,
                    entity_id=entity_id,
                    record_type=rec_type,
                    stage=1,
                    target_database=settings.INTERFACE_DB_NAME,
                    target_schema="CustomerInterfaceModule",
                    target_table="LongTermCareFunctionalScreenFormRaw",
                    target_column="RawText",
                    expected_value=exp_text[:200],
                    actual_value=exp_text[:200],
                    status="PASS",
                ))
            else:
                # Check if the entity exists at all (partial match on ID prefix)
                entity_exists = any(a.startswith(entity_id) for a in actual_texts)
                if entity_exists:
                    # Row exists but content differs
                    actual_for_entity = next((a for a in actual_texts if a.startswith(entity_id)), "")
                    result.add_mismatch(MismatchRecord(
                        source_line_number=line_num,
                        entity_id=entity_id,
                        record_type=rec_type,
                        stage=1,
                        target_database=settings.INTERFACE_DB_NAME,
                        target_schema="CustomerInterfaceModule",
                        target_table="LongTermCareFunctionalScreenFormRaw",
                        target_column="RawText",
                        expected_value=exp_text[:200],
                        actual_value=actual_for_entity[:200],
                        status="FAIL",
                        error_category="FieldMismatch",
                    ))
                else:
                    result.add_mismatch(MismatchRecord(
                        source_line_number=line_num,
                        entity_id=entity_id,
                        record_type=rec_type,
                        stage=1,
                        target_database=settings.INTERFACE_DB_NAME,
                        target_schema="CustomerInterfaceModule",
                        target_table="LongTermCareFunctionalScreenFormRaw",
                        target_column="(entire row)",
                        expected_value=f"Line {line_num}",
                        actual_value=None,
                        status="MISSING",
                        error_category="MissingRow",
                    ))

        return result

    # =========================================================================
    # Stage 2: Compare parsed fields (Checksum-first)
    # =========================================================================

    def compare_stage2(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """
        Compare expected parsed fields against actual LongTermCareFunctionalScreenForm table.

        D12 has one row per member in LongTermCareFunctionalScreenForm with all
        parsed fields as typed columns.
        """
        result = ComparatorResult()

        try:
            actual_rows = db.execute_query(
                DatabaseManager.INTERFACE,
                """
                SELECT
                    MemberId, FirstName, LastName, MiddleName,
                    ApplicantPrefersToLiveCode, GuardianPreferenceForLivingCode,
                    BathingHelpCode, BathingAdaptiveEquipmentCode,
                    DressingHelpCode, EatingHelpCode,
                    MobilityHelpCode, MobilityAdaptiveEquipmentCode,
                    ToiletingHelpCode, ToiletingAdaptiveEquipmentCode,
                    TransferringHelpCode, TransferringAdaptiveEquipmentCode,
                    MealPreparationHelpLevelCode, MedicationManagementHelpLevelCode,
                    MoneyManagementHelpLevelCode, LaundryChoresHelpLevelCode,
                    TelephoneUseAbilityCode, TelephoneAccessCode,
                    TransportationDrivingCode, OvernightCareSupervisionCode,
                    EmploymentStatusCode, WorkshopEmploymentFlag,
                    IndividualInterestInWorkingInCommunityCode,
                    CommunityEmploymentFlag, VocationalEmploymentFlag,
                    HomeEmploymentFlag, EmploymentAssistanceCode,
                    BehaviorsRequiringInterventionsCode, ExercisesRangeOfMotionCode,
                    MedicationsFluidFlushCode, MedicationAdministrationCode,
                    PainMedicationManagementCode, OstomyCode,
                    ChairBedPositioningCode, OxygenRespiratoryTreatmentCode,
                    InHomeDialysisCode, TotalParenteralNutritionCode,
                    TransfusionCode, TracheostomyCode,
                    TubeFeedingCode, UlcerStageTwoCode,
                    UlcerStageThreeFourCode, UrinaryCatheterCode,
                    OtherWoundCareCode, VentilatorInterventionCode,
                    NursingAssessmentCode, OtherServiceCode,
                    OtherServiceText, SkilledTherapyCode,
                    CommunicationCode, MemoryImpairmentFlag,
                    ShortTermMemoryLossFlag, UnableToRememberFlag,
                    LongTermMemoryLossFlag, UnableToDetermineText,
                    DailyDecisionMakingCode, PhysicallyResistiveToCareCode,
                    WanderingCode, SelfInjuriousBehaviorCode,
                    OffensiveBehaviorToOthersCode, MentalHealthNeedCode,
                    SubstanceAbuseFlag, SubstanceAbuseCurrentFlag,
                    SubstanceAbusePastFlag,
                    CONVERT(varchar(8), EligibilityCalculatedDate, 112) AS EligibilityCalculatedDate
                FROM [CustomerInterfaceModule].[LongTermCareFunctionalScreenForm]
                WHERE MemberId LIKE ?
                """,
                (f"{self.entity_id_prefix}%",),
            )
        except Exception as e:
            import logging
            logging.getLogger(__name__).error(f"Stage 2 query failed: {e}")
            actual_rows = []

        actual_by_id: Dict[str, Dict] = {}
        for row in actual_rows:
            mid = str(row.get("MemberId", "")).strip()
            if mid:
                actual_by_id[mid] = row

        # Group expectations by (entity_id, line_number) to form logical rows
        logical_rows: Dict[tuple, List[Dict]] = {}
        for exp in expected_rows:
            key = (exp["entity_id"], exp["line_number"])
            logical_rows.setdefault(key, []).append(exp)

        for (medicaid_id, line_num), columns in logical_rows.items():
            # Build expected column→value map
            expected_cols: Dict[str, str] = {}
            for exp in columns:
                expected_cols[exp["column_name"]] = exp["expected_value"] or ""

            actual = actual_by_id.get(medicaid_id)
            if not actual:
                for col_name, exp_val in expected_cols.items():
                    result.add_mismatch(MismatchRecord(
                        source_line_number=line_num,
                        entity_id=medicaid_id,
                        record_type="DTL",
                        stage=2,
                        target_database=settings.INTERFACE_DB_NAME,
                        target_schema="CustomerInterfaceModule",
                        target_table="LongTermCareFunctionalScreenForm",
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=None,
                        status="MISSING",
                        error_category="MissingRow",
                    ))
                continue

            # Check all columns at once
            all_match = True
            for col_name, exp_val in expected_cols.items():
                act_val = str(actual.get(col_name, "")).strip() if actual.get(col_name) is not None else ""
                if exp_val != act_val:
                    all_match = False
                    break

            if all_match:
                for col_name, exp_val in expected_cols.items():
                    result.add_pass(MismatchRecord(
                        source_line_number=line_num,
                        entity_id=medicaid_id,
                        record_type="DTL",
                        stage=2,
                        target_database=settings.INTERFACE_DB_NAME,
                        target_schema="CustomerInterfaceModule",
                        target_table="LongTermCareFunctionalScreenForm",
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=exp_val,
                        status="PASS",
                    ))
            else:
                for col_name, exp_val in expected_cols.items():
                    act_val = str(actual.get(col_name, "")).strip() if actual.get(col_name) is not None else ""
                    if exp_val == act_val:
                        result.add_pass(MismatchRecord(
                            source_line_number=line_num,
                            entity_id=medicaid_id,
                            record_type="DTL",
                            stage=2,
                            target_database=settings.INTERFACE_DB_NAME,
                            target_schema="CustomerInterfaceModule",
                            target_table="LongTermCareFunctionalScreenForm",
                            target_column=col_name,
                            expected_value=exp_val,
                            actual_value=act_val,
                            status="PASS",
                        ))
                    else:
                        result.add_mismatch(MismatchRecord(
                            source_line_number=line_num,
                            entity_id=medicaid_id,
                            record_type="DTL",
                            stage=2,
                            target_database=settings.INTERFACE_DB_NAME,
                            target_schema="CustomerInterfaceModule",
                            target_table="LongTermCareFunctionalScreenForm",
                            target_column=col_name,
                            expected_value=exp_val,
                            actual_value=act_val,
                            status="FAIL",
                            error_category="FieldMismatch",
                        ))

        return result

    # =========================================================================
    # Stage 3: SKIPPED for ICD-D12
    # =========================================================================

    def compare_stage3(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """
        Stage 3 is skipped for ICD-D12.

        The FSIA pipeline goes directly from Stage 2 (parsed fields in Interface DB)
        to Stage 4 (CustomFormModule tables in Carity DB). There is no intermediate
        transformation stage in the Interface DB for this interface.

        Returns an empty result (no checks performed).
        """
        return ComparatorResult()

    # =========================================================================
    # Stage 4: Compare against CustomFormModule tables in Carity DB
    # =========================================================================

    def compare_stage4(self, expected_rows: List[Dict[str, Any]]) -> ComparatorResult:
        """
        Compare Stage 4 — CustomFormModule tables in Carity DB.

        For ICD-D12, data flows directly from Stage 2 to Stage 4 (no Stage 3).
        Stage 4 targets CustomFormModule.CustomFormInstance (linked via
        CustomFormDefinitionKey) and associated FieldAnswer tables.
        """
        result = ComparatorResult()

        if not expected_rows:
            return result

        logical_rows: Dict[tuple, List[Dict]] = {}
        for row in expected_rows:
            key = (row["entity_id"], row["target_table"], row["row_key"])
            logical_rows.setdefault(key, []).append(row)

        tables_needed = set(row["target_table"] for row in expected_rows)
        actual_cache: Dict[str, List[Dict]] = {}
        for table_name in tables_needed:
            actual_cache[table_name] = self._query_stage4_table(table_name)

        for (medicaid_id, table_name, row_key), columns in logical_rows.items():
            expected_cols: Dict[str, str] = {}
            metadata: Dict[str, Dict] = {}
            for exp in columns:
                col_name = exp["target_column"]
                expected_cols[col_name] = exp["expected_value"] or ""
                metadata[col_name] = {
                    "business_rule": exp.get("business_rule"),
                    "vocab_used": exp.get("vocab_used"),
                }

            # Split schema.table for mismatch reporting
            if "." in table_name:
                schema, table_only = table_name.split(".", 1)
            else:
                schema, table_only = "CustomFormModule", table_name

            all_actual = actual_cache.get(table_name, [])
            member_rows = self._filter_member_rows(all_actual, medicaid_id)

            if not member_rows:
                for col_name, exp_val in expected_cols.items():
                    meta = metadata.get(col_name, {})
                    result.add_mismatch(MismatchRecord(
                        source_line_number=0,
                        entity_id=medicaid_id,
                        record_type="DTL",
                        stage=4,
                        target_database=settings.CARITY_DB_NAME,
                        target_schema=schema,
                        target_table=table_only,
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=None,
                        status="MISSING",
                        error_category="MissingRow",
                        business_rule=meta.get("business_rule"),
                        vocab_used=meta.get("vocab_used"),
                        notes=f"RowKey: {row_key}",
                    ))
                continue

            matched_row = self._find_full_match(member_rows, expected_cols)

            if matched_row is not None:
                for col_name, exp_val in expected_cols.items():
                    meta = metadata.get(col_name, {})
                    result.add_pass(MismatchRecord(
                        source_line_number=0,
                        entity_id=medicaid_id,
                        record_type="DTL",
                        stage=4,
                        target_database=settings.CARITY_DB_NAME,
                        target_schema=schema,
                        target_table=table_only,
                        target_column=col_name,
                        expected_value=exp_val,
                        actual_value=exp_val,
                        status="PASS",
                        business_rule=meta.get("business_rule"),
                        vocab_used=meta.get("vocab_used"),
                        notes=f"RowKey: {row_key}",
                    ))
            else:
                best_row = self._find_closest_row(member_rows, expected_cols)
                for col_name, exp_val in expected_cols.items():
                    meta = metadata.get(col_name, {})
                    act_val = str(best_row.get(col_name, "")).strip() if best_row.get(col_name) is not None else ""
                    if exp_val == act_val:
                        result.add_pass(MismatchRecord(
                            source_line_number=0,
                            entity_id=medicaid_id,
                            record_type="DTL",
                            stage=4,
                            target_database=settings.CARITY_DB_NAME,
                            target_schema=schema,
                            target_table=table_only,
                            target_column=col_name,
                            expected_value=exp_val,
                            actual_value=act_val,
                            status="PASS",
                            business_rule=meta.get("business_rule"),
                            vocab_used=meta.get("vocab_used"),
                            notes=f"RowKey: {row_key}",
                        ))
                    else:
                        result.add_mismatch(MismatchRecord(
                            source_line_number=0,
                            entity_id=medicaid_id,
                            record_type="DTL",
                            stage=4,
                            target_database=settings.CARITY_DB_NAME,
                            target_schema=schema,
                            target_table=table_only,
                            target_column=col_name,
                            expected_value=exp_val,
                            actual_value=act_val,
                            status="FAIL",
                            error_category="FieldMismatch",
                            business_rule=meta.get("business_rule"),
                            vocab_used=meta.get("vocab_used"),
                            notes=f"RowKey: {row_key}",
                        ))

        return result

    # =========================================================================
    # Query helpers
    # =========================================================================

    def _query_stage4_table(self, table_name: str) -> List[Dict]:
        """Query a Stage 4 table in the Carity DB. Handles dot-notation (Schema.Table)."""
        try:
            if "." in table_name:
                schema, table = table_name.split(".", 1)
            else:
                schema, table = "CustomFormModule", table_name

            # For CustomFormInstance, filter by the LTC form definition key
            if table == "CustomFormInstance":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT * FROM [{schema}].[{table}]
                        WHERE CustomFormDefinitionKey = ?""",
                    ("964B0DFB-ED99-4F5A-8449-B43C013B9062",),
                )
            # For CaseCustomFormInstance, join through CustomFormInstance to filter
            elif table == "CaseCustomFormInstance":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"""SELECT ccfi.* FROM [{schema}].[{table}] ccfi
                        INNER JOIN [{schema}].[CustomFormInstance] cfi
                            ON ccfi.CustomFormInstanceKey = cfi.CustomFormInstanceKey
                        WHERE cfi.CustomFormDefinitionKey = ?""",
                    ("964B0DFB-ED99-4F5A-8449-B43C013B9062",),
                )
            # For FieldAnswerBase and answer tables, join through CustomFormInstance
            elif table in ("FieldAnswerBase", "SimpleSingleSelectFieldAnswer", "DateFieldAnswer"):
                if table == "FieldAnswerBase":
                    return db.execute_query(
                        DatabaseManager.CARITY,
                        f"""SELECT fab.* FROM [{schema}].[{table}] fab
                            INNER JOIN [{schema}].[CustomFormInstance] cfi
                                ON fab.CustomFormInstanceKey = cfi.CustomFormInstanceKey
                            WHERE cfi.CustomFormDefinitionKey = ?""",
                        ("964B0DFB-ED99-4F5A-8449-B43C013B9062",),
                    )
                else:
                    # SimpleSingleSelectFieldAnswer / DateFieldAnswer join via FieldAnswerBase
                    return db.execute_query(
                        DatabaseManager.CARITY,
                        f"""SELECT ans.* FROM [{schema}].[{table}] ans
                            INNER JOIN [{schema}].[FieldAnswerBase] fab
                                ON ans.FieldAnswerBaseKey = fab.FieldAnswerBaseKey
                            INNER JOIN [{schema}].[CustomFormInstance] cfi
                                ON fab.CustomFormInstanceKey = cfi.CustomFormInstanceKey
                            WHERE cfi.CustomFormDefinitionKey = ?""",
                        ("964B0DFB-ED99-4F5A-8449-B43C013B9062",),
                    )
            # For PersonModule tables (PersonEmployment), filter by entity prefix
            elif schema == "PersonModule":
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"SELECT TOP 1000 * FROM [{schema}].[{table}]",
                )
            else:
                return db.execute_query(
                    DatabaseManager.CARITY,
                    f"SELECT TOP 1000 * FROM [{schema}].[{table}]",
                )
        except Exception:
            return []

    # =========================================================================
    # Checksum-first matching helpers
    # =========================================================================

    def _filter_member_rows(self, rows: List[Dict], medicaid_id: str) -> List[Dict]:
        """Filter actual rows to those belonging to a specific member."""
        id_columns = ["MedicaidId", "CustomerPersonIdentifier", "PersonIdentifier", "ExternalIdentifier"]
        member_rows = []
        for row in rows:
            has_id_col = False
            for id_col in id_columns:
                if id_col in row:
                    has_id_col = True
                    val = str(row.get(id_col, "")).strip()
                    if val == medicaid_id:
                        member_rows.append(row)
                    break
            if not has_id_col:
                member_rows.append(row)
        return member_rows

    def _find_full_match(self, actual_rows: List[Dict], expected_cols: Dict[str, str]) -> Optional[Dict]:
        """
        Find an actual row where ALL expected columns match exactly.
        Returns the matched row, or None if no perfect match exists.
        """
        for actual_row in actual_rows:
            all_match = True
            for col_name, exp_val in expected_cols.items():
                act_val = str(actual_row.get(col_name, "")).strip() if actual_row.get(col_name) is not None else ""
                if exp_val != act_val:
                    all_match = False
                    break
            if all_match:
                return actual_row
        return None

    def _find_closest_row(self, actual_rows: List[Dict], expected_cols: Dict[str, str]) -> Dict:
        """
        Find the actual row with the fewest column differences from expected.
        Used when no perfect match exists to provide the best diagnostic output.
        """
        if not actual_rows:
            return {}
        if len(actual_rows) == 1:
            return actual_rows[0]

        best_row = actual_rows[0]
        best_score = -1

        for actual_row in actual_rows:
            score = 0
            for col_name, exp_val in expected_cols.items():
                act_val = str(actual_row.get(col_name, "")).strip() if actual_row.get(col_name) is not None else ""
                if exp_val == act_val:
                    score += 1
            if score > best_score:
                best_score = score
                best_row = actual_row

        return best_row
